### ISSUE TITLE
Tag typo makes 'go mod' failing to retrieve the correct version.

### ISSUE THREAD

**Issue by shenwei356** [will-rowe/ntHash#4]
Hi Will, the last tag seems a typo `v03.0` : https://github.com/will-rowe/nthash/releases/tag/v03.0 

I just begin to use `go mode`, but it failed to parse `v03.0` and retrieved the `v0.2.0` as the lastest version.

**Comment by will-rowe** [comment]
Sorry about - I've re-tagged it so it should work now!

**Comment by shenwei356** [comment]
Thanks!
